/-
Copyright (c) 2026 FrenzyMath. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Anderson.Jensen.CloseUp.IntersectionHelpers
import Anderson.Jensen.CloseUp.TwoGen

/-!
# Close-up: B2 sub-case

The B2 sub-case of the well-founded close-up induction: a common
prime p divides every element of s' but divides neither a nor c.
The argument splits on whether the ideal generated by s' is zero
or not, and reduces to the factor and intersection cases.
-/

noncomputable section

open Cardinal Ideal

variable {T : Type*} [CommRing T] [IsLocalRing T] [IsNoetherianRing T] [IsDomain T]

theorem close_up_aux_b2_nonzero
    [IsAdicComplete (IsLocalRing.maximalIdeal T) T]
    (hM_not_assoc : ∀ (r : T), r ≠ 0 →
      IsLocalRing.maximalIdeal T ∉ associatedPrimes T (T ⧸ Ideal.span {r}))
    (hAss_ht : ∀ (r : T), r ≠ 0 →
      ∀ P ∈ associatedPrimes T (T ⧸ Ideal.span {r}), P.height ≤ 1)
    (hT_card : Cardinal.mk T = Cardinal.mk (IsLocalRing.ResidueField T))
    (hT_aleph0 : Cardinal.aleph0 < Cardinal.mk T)
    (n'' : ℕ)
    (ih : ∀ (R : NSubring T) (_ : Cardinal.mk R.carrier < Cardinal.mk T)
      (s : Finset R.carrier) (_ : s.card ≤ n'' + 1 + 1) (c : R.carrier)
      (_ : (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier))),
      ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
        (⟨(c : T), hle c.2⟩ : S.carrier) ∈
          Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)))
    (m : ℕ)
    (ih_m : ∀ m_1, m_1 < m →
      ∀ (R : NSubring T) (_ : Cardinal.mk R.carrier < Cardinal.mk T),
      letI : IsDomain R.carrier := NSubring.isDomain R
      letI : UniqueFactorizationMonoid R.carrier := R.isUFD
      ∀ (a : R.carrier) (s : Finset R.carrier),
      gcd_complexity s ≤ m_1 →
      s.card = n'' + 1 + 1 + 1 → a ∈ s → ∀ (c : R.carrier),
      (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier)) →
      ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
        (⟨(c : T), hle c.2⟩ : S.carrier) ∈
          Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)))
    {R : NSubring T} (hR_card : Cardinal.mk R.carrier < Cardinal.mk T)
    [IsDomain R.carrier] [UniqueFactorizationMonoid R.carrier] [DecidableEq R.carrier]
    {a : R.carrier} {s : Finset R.carrier}
    (hs_gcd : gcd_complexity s ≤ m)
    (hs_eq : s.card = n'' + 1 + 1 + 1) (ha_mem : a ∈ s)
    {c : R.carrier}
    (s' : Finset R.carrier) (hs'_def : s' = s.erase a)
    (hs_insert : s = insert a s')
    (hs'_card : s'.card ≤ n'' + 1 + 1)
    {p : R.carrier} (hp : Prime p) (hp_dvd : ∀ x ∈ s', p ∣ x)
    (hpa : ¬p ∣ a)
    (_hgcd_factor : ∀ (q : R.carrier), Prime q → (∀ x ∈ s', q ∣ x) → ¬q ∣ a ∧ ¬q ∣ c)
    (t : T) (u : T) (v : T)
    (hv : v ∈ Ideal.map R.carrier.subtype (span (↑s' : Set R.carrier)))
    (ht_eq : u = R.carrier.subtype a * t)
    (huv : u + v = (c : T))
    (ha_zero : (a : T) ≠ 0)
    (_hI_s'_bot : Ideal.map R.carrier.subtype (span (↑s' : Set R.carrier)) ≠ ⊥) :
    ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
      (⟨(c : T), hle c.2⟩ : S.carrier) ∈
        Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)) := by
  by_cases hM_bot : IsLocalRing.maximalIdeal T = ⊥
  · -- M = ⊥: T is a field, a is a unit, trivial
    refine ⟨R, ⟨le_refl _, fun r hr => hr, le_max_right _ _⟩,
        le_refl _, ?_⟩
    have h_id : Subring.inclusion (le_refl R.carrier) =
        RingHom.id R.carrier := RingHom.ext fun x => Subtype.ext rfl
    change (⟨(c : T), le_refl R.carrier c.2⟩ : R.carrier) ∈
      Ideal.map (Subring.inclusion (le_refl R.carrier))
        (span (↑s : Set R.carrier))
    rw [h_id, Ideal.map_id]
    have ha_unit : IsUnit a := by
      by_contra h
      have hmem := (IsLocalRing.mem_maximalIdeal _).mpr h
      rw [R.maximal_ideal_eq, Ideal.mem_comap, hM_bot,
        Submodule.mem_bot] at hmem
      exact ha_zero hmem
    rw [Ideal.eq_top_of_isUnit_mem _
      (Ideal.subset_span (Finset.mem_coe.mpr ha_mem)) ha_unit]
    exact Submodule.mem_top
  · -- M ≠ ⊥: intersection_close_up with coprime pair (a, p), then GCD induction
    -- Step 1: Show c ∈ span{(a:T), (p:T)}
    have hspan_s'_le_p : span (↑s' : Set R.carrier) ≤ span {p} :=
      Ideal.span_le.mpr fun x hx =>
        Ideal.mem_span_singleton.mpr (hp_dvd x (Finset.mem_coe.mp hx))
    have hv_p : v ∈ Ideal.map R.carrier.subtype (span {p}) :=
      Ideal.map_mono hspan_s'_le_p hv
    rw [Ideal.map_span, Set.image_singleton] at hv_p
    have hu_a : u ∈ Ideal.span {(a : T)} :=
      Ideal.mem_span_singleton.mpr ⟨t, ht_eq⟩
    have hc_ap : (c : T) ∈ Ideal.span {(a : T), (p : T)} := by
      rw [Ideal.span_insert]
      exact Submodule.mem_sup.mpr ⟨u, hu_a, v, hv_p, huv⟩
    -- Step 2: Show a and p are coprime
    have hcoprime_ap : ∀ q : R.carrier, Prime q → ¬(q ∣ a ∧ q ∣ p) := by
      intro q hq ⟨hqa, hqp⟩
      -- q | p and both prime → q ~ᵤ p → p | a, contradicting hpa
      exact hpa ((hq.irreducible.associated_of_dvd
        hp.irreducible hqp).dvd_iff_dvd_left.mp hqa)
    have ha_ne : (↑a : T) ≠ 0 := ha_zero
    have hp_ne : (↑p : T) ≠ 0 := fun h =>
      hp.ne_zero (Subtype.val_injective h)
    -- Step 3: Apply intersection_close_up
    obtain ⟨S₁, hAext₁, hle₁, x₁, hrem₁⟩ :=
      intersection_close_up R a p c hc_ap hcoprime_ap
        ha_ne hp_ne hM_bot hM_not_assoc hAss_ht hR_card hT_card
    -- Step 4: Extract w from hrem₁
    haveI : IsDomain S₁.carrier := NSubring.isDomain S₁
    haveI : UniqueFactorizationMonoid S₁.carrier := S₁.isUFD
    obtain ⟨w, hw_eq⟩ := Ideal.mem_span_singleton.mp hrem₁
    have hS₁_card : Cardinal.mk S₁.carrier < Cardinal.mk T :=
      lt_of_le_of_lt hAext₁.card_le (max_lt hT_aleph0 hR_card)
    -- Step 5: Build divided set s'_div = s'/p
    classical
    let div_p_b2 : R.carrier → R.carrier :=
      fun x => if h : p ∣ x then Classical.choose h else x
    have hdiv_b2 : ∀ x ∈ s', x = p * div_p_b2 x := by
      intro x hx
      change x = p * (if h : p ∣ x then Classical.choose h else x)
      rw [dif_pos (hp_dvd x hx)]
      exact Classical.choose_spec (hp_dvd x hx)
    let s'_div := s'.image div_p_b2
    have h_ie_b2 : span (↑s' : Set R.carrier) =
        span {p} * span (↑s'_div : Set R.carrier) :=
      span_eq_mul_span_image_div p s' hp_dvd div_p_b2 hdiv_b2
    have h_ml_b2 : span {p} * span (↑(insert a s'_div) : Set R.carrier) ≤
        span (↑(insert a s') : Set R.carrier) :=
      prime_mul_span_insert_le p a s' div_p_b2 hdiv_b2
    set t_val_b2 := t with ht_val_b2_def
    have ht_eq_b2 : u = (a : T) * t_val_b2 := ht_eq
    have huv_b2 : u + v = (c : T) := huv
    have hv_pT : v ∈ Ideal.span {(p : T)} := by
      have h1 := Ideal.map_mono hspan_s'_le_p hv
      rwa [Ideal.map_span, Set.image_singleton] at h1
    obtain ⟨w_b2, hw_b2_eq⟩ := Ideal.mem_span_singleton.mp hv_pT
    have hw_b2_span : w_b2 ∈ Ideal.map R.carrier.subtype (span (↑s'_div : Set R.carrier)) := by
      have hv' := hv
      rw [h_ie_b2, Ideal.map_mul, Ideal.map_span, Set.image_singleton,
        Ideal.mem_span_singleton_mul] at hv'
      obtain ⟨z, hz, hpz⟩ := hv'
      have : z = w_b2 := mul_left_cancel₀ hp_ne (hpz.trans hw_b2_eq)
      exact this ▸ hz
    -- Cross-ring regularity: a*(x₁ - t_val_b2) ∈ span{p} → x₁ - t_val_b2 ∈ span{p}
    have h_eq_T : (a : T) * (↑x₁ : T) + (p : T) * (↑w : T) =
        (a : T) * t_val_b2 + (p : T) * w_b2 := by
      have h1 : (c : T) = (↑x₁ : T) * (a : T) + (p : T) * (↑w : T) := by
        have := congr_arg Subtype.val hw_eq
        simp only [Subring.coe_mul, AddSubgroupClass.coe_sub] at this
        linear_combination this
      have h2 : (c : T) = (a : T) * t_val_b2 + (p : T) * w_b2 := by
        have heq := huv_b2
        rw [ht_eq_b2, hw_b2_eq] at heq
        exact heq.symm
      linear_combination h2 - h1
    have h_diff_mem : (a : T) * ((↑x₁ : T) - t_val_b2) ∈ Ideal.span {(p : T)} := by
      have : (a : T) * ((↑x₁ : T) - t_val_b2) = (p : T) * (w_b2 - (↑w : T)) := by
        linear_combination h_eq_T
      rw [this]
      exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
    obtain ⟨t'_b2, ht'_b2⟩ := nzd_element_in_span_prime R p a hp hpa hM_not_assoc
      ((↑x₁ : T) - t_val_b2) h_diff_mem
    have hw_decomp : (↑w : T) = w_b2 - (a : T) * t'_b2 := by
      have h1 : (p : T) * (w_b2 - (↑w : T)) = (a : T) * ((↑x₁ : T) - t_val_b2) := by
        linear_combination -h_eq_T
      rw [ht'_b2] at h1
      have h2 : (p : T) * (w_b2 - (↑w : T)) = (p : T) * ((a : T) * t'_b2) := by
        linear_combination h1
      have h3 : w_b2 - (↑w : T) = (a : T) * t'_b2 := mul_left_cancel₀ hp_ne h2
      linear_combination -h3
    have hw_mem_T : (↑w : T) ∈
        Ideal.map R.carrier.subtype (span (↑(insert a s'_div) : Set R.carrier)) := by
      rw [hw_decomp]
      apply sub_mem
      · exact Ideal.map_mono
          (Ideal.span_mono (Finset.coe_subset.mpr (Finset.subset_insert a s'_div))) hw_b2_span
      · exact Ideal.map_mono
          (Ideal.span_mono
            (Set.singleton_subset_iff.mpr (Finset.mem_coe.mpr (Finset.mem_insert_self a s'_div))))
          (by rw [Ideal.map_span, Set.image_singleton]
              exact Ideal.mem_span_singleton.mpr ⟨t'_b2, rfl⟩)
    -- Suffices: find S₂ with w ∈ span(insert a s'_div)·S₂, then compose back
    suffices h_suff_main : ∃ S₂ : NSubring T, IsAExtension S₁ S₂ ∧
        ∃ (hle₂ : S₁.carrier ≤ S₂.carrier), (⟨(↑w : T), hle₂ w.2⟩ : S₂.carrier) ∈
          Ideal.map (Subring.inclusion hle₂)
            (Ideal.map (Subring.inclusion hle₁) (span (↑(insert a s'_div) : Set R.carrier))) by
      obtain ⟨S₂, hAext₂, hle₂, hw_S₂⟩ := h_suff_main
      have hle_comp : R.carrier ≤ S₂.carrier := le_trans hle₁ hle₂
      refine ⟨S₂, isAExtension_trans' hAext₁ hAext₂, hle_comp, ?_⟩
      have hc_val : (c : T) = (↑x₁ : T) * (a : T) + (p : T) * (↑w : T) := by
        have := congr_arg Subtype.val hw_eq
        simp only [Subring.coe_mul, AddSubgroupClass.coe_sub] at this
        linear_combination this
      change (⟨(c : T), hle_comp c.2⟩ : S₂.carrier) ∈
        Ideal.map (Subring.inclusion hle_comp)
          (span (↑s : Set R.carrier))
      rw [hs_insert]
      have hc_eq : (⟨(c : T), hle_comp c.2⟩ : S₂.carrier) =
          ⟨(↑x₁ : T), hle₂ x₁.2⟩ * ⟨(a : T), hle_comp a.2⟩ +
          ⟨(p : T), hle_comp p.2⟩ * ⟨(↑w : T), hle₂ w.2⟩ := by
        ext
        simp only [Subring.coe_mul, Subring.coe_add]
        exact hc_val
      rw [hc_eq]
      apply add_mem
      · apply Ideal.mul_mem_left
        exact Ideal.map_mono
          (Ideal.span_mono
            (Set.singleton_subset_iff.mpr (Finset.mem_coe.mpr (Finset.mem_insert_self a s'))))
          (Ideal.mem_map_of_mem _ (Ideal.subset_span rfl))
      · have hw_comp : (⟨(↑w : T), hle₂ w.2⟩ : S₂.carrier) ∈
            Ideal.map (Subring.inclusion hle_comp)
              (span (↑(insert a s'_div) : Set R.carrier)) := by
          rw [show Subring.inclusion hle_comp =
            (Subring.inclusion hle₂).comp (Subring.inclusion hle₁) from
            RingHom.ext fun _ => rfl, ← Ideal.map_map]
          exact hw_S₂
        have hmul := Ideal.mul_mem_mul
          (show (⟨(p : T), hle_comp p.2⟩ : S₂.carrier) ∈
            Ideal.map (Subring.inclusion hle_comp)
              (span {p}) from
            Ideal.mem_map_of_mem _
              (Ideal.subset_span rfl))
          hw_comp
        rw [← Ideal.map_mul] at hmul
        exact Ideal.map_mono h_ml_b2 hmul
    -- Now apply IH to S₁ with w and insert a s'_div
    by_cases ha_s'_div : a ∈ s'_div
    · -- a ∈ s'_div: insert = s'_div
      have h_eq2 : insert a s'_div = s'_div := Finset.insert_eq_of_mem ha_s'_div
      rw [h_eq2] at hw_mem_T ⊢
      have hs'_div_card : s'_div.card ≤ n'' + 1 + 1 := Finset.card_image_le.trans hs'_card
      let liftR₁ := Subring.inclusion hle₁
      let s₁ := s'_div.image liftR₁
      have hs₁_card : s₁.card ≤ n'' + 1 + 1 := Finset.card_image_le.trans hs'_div_card
      have hw_s₁ : (↑w : T) ∈
          Ideal.map S₁.carrier.subtype (span (↑s₁ : Set S₁.carrier)) := by
        change (↑w : T) ∈ Ideal.map S₁.carrier.subtype
          (span (↑(s'_div.image liftR₁) : Set S₁.carrier))
        rw [Finset.coe_image, ← Ideal.map_span, Ideal.map_map,
          show S₁.carrier.subtype.comp liftR₁ = R.carrier.subtype from
            RingHom.ext fun _ => rfl]
        exact hw_mem_T
      obtain ⟨S₂, hAext₂, hle₂, hw_S₂⟩ := ih S₁ hS₁_card s₁ hs₁_card w hw_s₁
      refine ⟨S₂, hAext₂, hle₂, ?_⟩
      convert hw_S₂ using 1
      congr 1
      rw [Ideal.map_span, ← Finset.coe_image]
    · -- a ∉ s'_div
      by_cases hs'_div_card : s'_div.card ≤ n'' + 1
      · -- |insert a s'_div| ≤ n''+2
        have h_ins_card3 : (insert a s'_div).card ≤ n'' + 1 + 1 := by
          rw [Finset.card_insert_of_notMem ha_s'_div]
          omega
        let liftR₁ := Subring.inclusion hle₁
        let s₁ := (insert a s'_div).image liftR₁
        have hs₁_card : s₁.card ≤ n'' + 1 + 1 := Finset.card_image_le.trans h_ins_card3
        have hw_s₁ : (↑w : T) ∈
            Ideal.map S₁.carrier.subtype (span (↑s₁ : Set S₁.carrier)) := by
          change (↑w : T) ∈ Ideal.map S₁.carrier.subtype
            (span (↑((insert a s'_div).image liftR₁) : Set S₁.carrier))
          rw [Finset.coe_image, ← Ideal.map_span, Ideal.map_map,
            show S₁.carrier.subtype.comp liftR₁ = R.carrier.subtype from
              RingHom.ext fun _ => rfl]
          exact hw_mem_T
        obtain ⟨S₂, hAext₂, hle₂, hw_S₂⟩ := ih S₁ hS₁_card s₁ hs₁_card w hw_s₁
        refine ⟨S₂, hAext₂, hle₂, ?_⟩
        convert hw_S₂ using 1
        congr 1
        rw [Ideal.map_span, ← Finset.coe_image]
      · -- s'_div.card = n''+2, need WF on GCD complexity
        push_neg at hs'_div_card
        have hs'_div_card_eq : s'_div.card = n'' + 1 + 1 := by
          have h_le : s'_div.card ≤ n'' + 1 + 1 := Finset.card_image_le.trans hs'_card
          omega
        let liftR₁' := Subring.inclusion hle₁
        let s₁' := (insert a s'_div).image liftR₁'
        have hw_s₁' : (↑w : T) ∈
            Ideal.map S₁.carrier.subtype (span (↑s₁' : Set S₁.carrier)) := by
          change (↑w : T) ∈ Ideal.map S₁.carrier.subtype
            (span (↑((insert a s'_div).image liftR₁') : Set S₁.carrier))
          rw [Finset.coe_image, ← Ideal.map_span, Ideal.map_map,
            show S₁.carrier.subtype.comp liftR₁' = R.carrier.subtype from
              RingHom.ext fun _ => rfl]
          exact hw_mem_T
        have hs₁'_card : s₁'.card = n'' + 1 + 1 + 1 := by
          rw [show s₁' = (insert a s'_div).image liftR₁' from rfl,
            Finset.card_image_of_injective _ (Subring.inclusion_injective hle₁),
            Finset.card_insert_of_notMem ha_s'_div, hs'_div_card_eq]
        have ha_s₁' : liftR₁' a ∈ s₁' :=
          Finset.mem_image.mpr ⟨a, Finset.mem_insert_self a s'_div, rfl⟩
        -- GCD complexity drops: gcd_complexity s₁' < m
        have hgcd_s₁' : gcd_complexity s₁' < m := by
          have hcross : gcd_complexity s₁' = gcd_complexity (insert a s'_div) := by
            unfold gcd_complexity
            have hinj₁ : Set.InjOn liftR₁' ↑(insert a s'_div) :=
              fun x _ y _ h => (Subring.inclusion_injective hle₁) h
            rw [show s₁' = (insert a s'_div).image liftR₁' from rfl,
                Finset.sum_image hinj₁]
            apply Finset.sum_congr rfl
            intro x _
            exact normalizedFactors_card_inclusion R S₁
              ⟨hAext₁.le, hAext₁.primes_preserved, hAext₁.card_le⟩
              hle₁ x
          have hstrict : gcd_complexity (insert a s'_div) < gcd_complexity s :=
            gcd_complexity_div_prime_strict hs_insert hs'_def
              (by
                 rw [hs'_def, Finset.card_erase_of_mem ha_mem, hs_eq]
                 omega)
              hp div_p_b2 hdiv_b2 ha_s'_div
          calc gcd_complexity s₁' = gcd_complexity (insert a s'_div) := hcross
            _ < gcd_complexity s := hstrict
            _ ≤ m := hs_gcd
        obtain ⟨S₂, hAext₂, hle₂, hw_S₂⟩ :=
          ih_m (gcd_complexity s₁') hgcd_s₁' S₁ hS₁_card (liftR₁' a) s₁' le_rfl hs₁'_card
            ha_s₁' w hw_s₁'
        refine ⟨S₂, hAext₂, hle₂, ?_⟩
        convert hw_S₂ using 1
        congr 1
        rw [Ideal.map_span, ← Finset.coe_image]

-- Extracted: Sub-case B2 of close_up_aux_wf (p∤a, no common prime divides both a and c).
theorem close_up_aux_b2
    [IsAdicComplete (IsLocalRing.maximalIdeal T) T]
    (hM_not_assoc : ∀ (r : T), r ≠ 0 →
      IsLocalRing.maximalIdeal T ∉ associatedPrimes T (T ⧸ Ideal.span {r}))
    (hAss_ht : ∀ (r : T), r ≠ 0 →
      ∀ P ∈ associatedPrimes T (T ⧸ Ideal.span {r}), P.height ≤ 1)
    (hT_card : Cardinal.mk T = Cardinal.mk (IsLocalRing.ResidueField T))
    (hT_aleph0 : Cardinal.aleph0 < Cardinal.mk T)
    (n'' : ℕ)
    (ih : ∀ (R : NSubring T) (_ : Cardinal.mk R.carrier < Cardinal.mk T)
      (s : Finset R.carrier) (_ : s.card ≤ n'' + 1 + 1) (c : R.carrier)
      (_ : (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier))),
      ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
        (⟨(c : T), hle c.2⟩ : S.carrier) ∈
          Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)))
    (m : ℕ)
    (ih_m : ∀ m_1, m_1 < m →
      ∀ (R : NSubring T) (_ : Cardinal.mk R.carrier < Cardinal.mk T),
      letI : IsDomain R.carrier := NSubring.isDomain R
      letI : UniqueFactorizationMonoid R.carrier := R.isUFD
      ∀ (a : R.carrier) (s : Finset R.carrier),
      gcd_complexity s ≤ m_1 →
      s.card = n'' + 1 + 1 + 1 → a ∈ s → ∀ (c : R.carrier),
      (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier)) →
      ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
        (⟨(c : T), hle c.2⟩ : S.carrier) ∈
          Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)))
    {R : NSubring T} (hR_card : Cardinal.mk R.carrier < Cardinal.mk T)
    [IsDomain R.carrier] [UniqueFactorizationMonoid R.carrier] [DecidableEq R.carrier]
    {a : R.carrier} {s : Finset R.carrier}
    (hs_gcd : gcd_complexity s ≤ m)
    (hs_eq : s.card = n'' + 1 + 1 + 1) (ha_mem : a ∈ s)
    {c : R.carrier}
    (hc : (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier)))
    (s' : Finset R.carrier) (hs'_def : s' = s.erase a)
    (hs_insert : s = insert a s')
    (hs'_card : s'.card ≤ n'' + 1 + 1)
    {p : R.carrier} (hp : Prime p) (hp_dvd : ∀ x ∈ s', p ∣ x)
    (hpa : ¬p ∣ a)
    (hgcd_factor : ¬∃ q : R.carrier, Prime q ∧ (∀ x ∈ s', q ∣ x) ∧ (q ∣ a ∨ q ∣ c)) :
    ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
      (⟨(c : T), hle c.2⟩ : S.carrier) ∈
        Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)) := by
  push_neg at hgcd_factor
  -- Decompose hc via span_insert
  rw [hs_insert, Finset.coe_insert, Ideal.span_insert, Ideal.map_sup] at hc
  obtain ⟨u, hu, v, hv, huv⟩ := Submodule.mem_sup.mp hc
  rw [Ideal.map_span, Set.image_singleton, Ideal.mem_span_singleton] at hu
  obtain ⟨t, ht_eq⟩ := hu
  have hv_eq : v = (c : T) - u := eq_sub_of_add_eq' huv
  -- Special case: a = 0
  by_cases ha_zero : (a : T) = 0
  · have hc_s' : (c : T) ∈ Ideal.map R.carrier.subtype
        (span (↑s' : Set R.carrier)) := by
      have hu_zero : u = 0 := by
        rw [ht_eq]
        change (a : T) * t = 0
        rw [ha_zero, zero_mul]
      rw [← huv, hu_zero, zero_add]
      exact hv
    obtain ⟨S, hAext, hle, hmem⟩ := ih R hR_card s' hs'_card c hc_s'
    exact ⟨S, hAext, hle,
      Ideal.map_mono (Ideal.span_mono (Finset.coe_subset.mpr
        (hs'_def ▸ Finset.erase_subset a s))) hmem⟩
  · -- a ≠ 0
    by_cases hI_s'_bot : Ideal.map R.carrier.subtype
        (span (↑s' : Set R.carrier)) = ⊥
    · -- I_s' = 0: close_up_dvd
      have hv_zero : v = 0 := (Submodule.mem_bot T).mp (hI_s'_bot ▸ hv)
      have hc_aT : (c : T) ∈ span {(a : T)} := by
        rw [← huv, hv_zero, add_zero, ht_eq]
        exact Ideal.mem_span_singleton.mpr ⟨t, rfl⟩
      refine ⟨R, ⟨le_refl _, fun r hr => hr, le_max_right _ _⟩, le_refl _, ?_⟩
      have h_id : Subring.inclusion (le_refl R.carrier) =
          RingHom.id R.carrier := RingHom.ext fun x => Subtype.ext rfl
      have hcR := close_up_dvd R a c hc_aT
      change (⟨(c : T), le_refl R.carrier c.2⟩ : R.carrier) ∈
        Ideal.map (Subring.inclusion (le_refl R.carrier))
          (span (↑s : Set R.carrier))
      rw [h_id, Ideal.map_id, hs_insert, Finset.coe_insert]
      exact Ideal.span_mono
        (Set.singleton_subset_iff.mpr (Set.mem_insert a _)) hcR
    · exact close_up_aux_b2_nonzero hM_not_assoc hAss_ht hT_card hT_aleph0 n'' ih m ih_m
        hR_card hs_gcd hs_eq ha_mem s' hs'_def hs_insert hs'_card hp hp_dvd hpa
        hgcd_factor t u v hv ht_eq huv ha_zero hI_s'_bot


end
