/-
Copyright (c) 2026 FrenzyMath. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Anderson.Jensen.CloseUp.GcdComplexity

/-!
# Close-up: intersection helpers

Auxiliary lemmas for the intersection sub-case of the close-up
well-founded induction. Handles the situation where the ideal
generated by s' has large intersection with a prime, and proves
the strict decrease of GCD complexity after dividing by a common
prime factor.
-/

noncomputable section

open Cardinal Ideal

variable {T : Type*} [CommRing T] [IsLocalRing T] [IsNoetherianRing T] [IsDomain T]

theorem close_up_aux_factor_intersection_large
    [IsAdicComplete (IsLocalRing.maximalIdeal T) T]
    (n'' : ℕ)
    (ih : ∀ (R : NSubring T) (_ : Cardinal.mk R.carrier < Cardinal.mk T)
      (s : Finset R.carrier) (_ : s.card ≤ n'' + 1 + 1) (c : R.carrier)
      (_ : (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier))),
      ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
        (⟨(c : T), hle c.2⟩ : S.carrier) ∈
          Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)))
    (m : ℕ)
    (ih_m : ∀ m_1, m_1 < m →
      ∀ (R : NSubring T) (_ : Cardinal.mk R.carrier < Cardinal.mk T),
      letI : IsDomain R.carrier := NSubring.isDomain R
      letI : UniqueFactorizationMonoid R.carrier := R.isUFD
      ∀ (a : R.carrier) (s : Finset R.carrier),
      gcd_complexity s ≤ m_1 →
      s.card = n'' + 1 + 1 + 1 → a ∈ s → ∀ (c : R.carrier),
      (c : T) ∈ Ideal.map R.carrier.subtype (span (↑s : Set R.carrier)) →
      ∃ S : NSubring T, IsAExtension R S ∧ ∃ (hle : R.carrier ≤ S.carrier),
        (⟨(c : T), hle c.2⟩ : S.carrier) ∈
          Ideal.map (Subring.inclusion hle) (span (↑s : Set R.carrier)))
    {R : NSubring T}
    [IsDomain R.carrier] [UniqueFactorizationMonoid R.carrier] [DecidableEq R.carrier]
    {a : R.carrier}
    {s : Finset R.carrier}
    (hs_gcd : gcd_complexity s ≤ m)
    (rest : Finset R.carrier)
    (_hrest_card : rest.card ≤ n'' + 1 + 1)
    (ha_rest : a ∉ rest)
    {b : R.carrier} (hb_rest : b ∈ rest)
    (hgcd_rest : gcd_complexity (insert a rest) ≤ gcd_complexity s)
    {q' : R.carrier} (hq' : Prime q')
    (_hq'_dvd : ∀ x ∈ rest, q' ∣ x)
    {S₁ : NSubring T} (hAext₁ : IsAExtension R S₁)
    (hle₁ : R.carrier ≤ S₁.carrier)
    (hS₁_card : Cardinal.mk S₁.carrier < Cardinal.mk T)
    [IsDomain S₁.carrier] [UniqueFactorizationMonoid S₁.carrier]
    (w : S₁.carrier)
    (div_q_b2 : R.carrier → R.carrier)
    (hdiv_b2 : ∀ x ∈ rest, x = q' * div_q_b2 x)
    (rest'2 : Finset R.carrier)
    (hrest'2_def : rest'2 = rest.image div_q_b2)
    (_h_ml_b2 : span {q'} * span (↑(insert a rest'2) : Set R.carrier) ≤
      span (↑(insert a rest) : Set R.carrier))
    (hw_mem_T : (↑w : T) ∈ Ideal.map R.carrier.subtype
      (span (↑(insert a rest'2) : Set R.carrier)))
    (ha_rest'2 : a ∉ rest'2)
    (hrest'2_card : rest'2.card = n'' + 1 + 1)
    (hb_rest'2 : div_q_b2 b ∈ rest'2) :
    ∃ S₂ : NSubring T,
      IsAExtension S₁ S₂ ∧
      ∃ (hle₂ : S₁.carrier ≤ S₂.carrier),
        (⟨(↑w : T), hle₂ w.2⟩ : S₂.carrier) ∈
        Ideal.map (Subring.inclusion hle₂)
          (Ideal.map (Subring.inclusion hle₁)
            (span (↑(insert a rest'2) : Set R.carrier))) := by
  classical
  by_cases hdb2_zero : div_q_b2 b = 0
  · have hspan_eq_b2 : span (↑rest'2 : Set R.carrier) =
        span (↑(rest'2.erase (div_q_b2 b)) : Set R.carrier) := by
      apply le_antisymm
      · apply Ideal.span_le.mpr
        intro x hx
        rcases eq_or_ne x (div_q_b2 b) with rfl | hne
        · rw [hdb2_zero]
          exact zero_mem _
        · exact Ideal.subset_span
            (Finset.mem_coe.mpr (Finset.mem_erase.mpr ⟨hne, Finset.mem_coe.mp hx⟩))
      · exact Ideal.span_mono (Finset.coe_subset.mpr (Finset.erase_subset _ _))
    have h_erase_card2 : (rest'2.erase (div_q_b2 b)).card ≤ n'' + 1 := by
      rw [Finset.card_erase_of_mem hb_rest'2, hrest'2_card]
      omega
    have h_ins_card4 : (insert a (rest'2.erase (div_q_b2 b))).card ≤ n'' + 1 + 1 := by
      rw [Finset.card_insert_of_notMem (fun h => ha_rest'2 ((Finset.erase_subset _ _) h))]
      omega
    have hw_mem_T2 : (↑w : T) ∈ Ideal.map R.carrier.subtype
        (span (↑(insert a (rest'2.erase (div_q_b2 b))) : Set R.carrier)) := by
      have hspan_le2 : span (↑(insert a rest'2) : Set R.carrier) ≤
          span (↑(insert a (rest'2.erase (div_q_b2 b))) : Set R.carrier) := by
        apply Ideal.span_le.mpr
        intro x hx
        rw [Finset.mem_coe, Finset.mem_insert] at hx
        rcases hx with hxa | hx'
        · rw [hxa]
          exact Ideal.subset_span (Finset.mem_coe.mpr (Finset.mem_insert_self _ _))
        · rcases eq_or_ne x (div_q_b2 b) with rfl | hne
          · rw [hdb2_zero]
            exact zero_mem _
          · exact Ideal.subset_span
              (Finset.mem_coe.mpr (Finset.mem_insert_of_mem (Finset.mem_erase.mpr ⟨hne, hx'⟩)))
      exact Ideal.map_mono hspan_le2 hw_mem_T
    let liftR₁ := Subring.inclusion hle₁
    let s₁ := (insert a (rest'2.erase (div_q_b2 b))).image liftR₁
    have hs₁_card : s₁.card ≤ n'' + 1 + 1 := Finset.card_image_le.trans h_ins_card4
    have hw_s₁ : (↑w : T) ∈
        Ideal.map S₁.carrier.subtype (span (↑s₁ : Set S₁.carrier)) := by
      change (↑w : T) ∈ Ideal.map S₁.carrier.subtype
        (span (↑((insert a (rest'2.erase (div_q_b2 b))).image liftR₁) : Set S₁.carrier))
      rw [Finset.coe_image, ← Ideal.map_span, Ideal.map_map,
        show S₁.carrier.subtype.comp liftR₁ = R.carrier.subtype from
          RingHom.ext fun _ => rfl]
      exact hw_mem_T2
    obtain ⟨S₂, hAext₂, hle₂, hw_S₂⟩ := ih S₁ hS₁_card s₁ hs₁_card w hw_s₁
    refine ⟨S₂, hAext₂, hle₂, ?_⟩
    have h_mono : Ideal.map (Subring.inclusion hle₂)
        (Ideal.map liftR₁ (span (↑(insert a (rest'2.erase (div_q_b2 b))) : Set R.carrier))) ≤
        Ideal.map (Subring.inclusion hle₂)
          (Ideal.map liftR₁ (span (↑(insert a rest'2) : Set R.carrier))) :=
      Ideal.map_mono (Ideal.map_mono
        (Ideal.span_mono
          (Finset.coe_subset.mpr (Finset.insert_subset_insert _ (Finset.erase_subset _ _)))))
    apply h_mono
    convert hw_S₂ using 1
    congr 1
    rw [Ideal.map_span, ← Finset.coe_image]
  · by_cases hdb2_unit : IsUnit (div_q_b2 b)
    · refine ⟨S₁, ⟨le_refl _, fun r hr => hr, le_max_right _ _⟩, le_refl _, ?_⟩
      have h_id2 : Subring.inclusion (le_refl S₁.carrier) = RingHom.id S₁.carrier :=
        RingHom.ext fun x => Subtype.ext rfl
      rw [h_id2, Ideal.map_id]
      have htop : span (↑(insert a rest'2) : Set R.carrier) = ⊤ :=
        Ideal.eq_top_of_isUnit_mem _
          (Ideal.subset_span (Finset.mem_coe.mpr (Finset.mem_insert_of_mem hb_rest'2)))
          hdb2_unit
      rw [htop, Ideal.map_top]
      exact Submodule.mem_top
    · let liftR₁' := Subring.inclusion hle₁
      let s₁' := (insert a rest'2).image liftR₁'
      have hw_s₁' : (↑w : T) ∈
          Ideal.map S₁.carrier.subtype (span (↑s₁' : Set S₁.carrier)) := by
        change (↑w : T) ∈ Ideal.map S₁.carrier.subtype
          (span (↑((insert a rest'2).image liftR₁') : Set S₁.carrier))
        rw [Finset.coe_image, ← Ideal.map_span, Ideal.map_map,
          show S₁.carrier.subtype.comp liftR₁' = R.carrier.subtype from
            RingHom.ext fun _ => rfl]
        exact hw_mem_T
      have h_inj₁' : Function.Injective liftR₁' :=
        Subring.inclusion_injective hle₁
      have hs₁'_card : s₁'.card = n'' + 1 + 1 + 1 := by
        have h1 : s₁'.card = (insert a rest'2).card :=
          Finset.card_image_of_injective _ h_inj₁'
        rw [h1, Finset.card_insert_of_notMem ha_rest'2, hrest'2_card]
      have ha_s₁' : liftR₁' a ∈ s₁' :=
        Finset.mem_image_of_mem _ (Finset.mem_insert_self a rest'2)
      have hgcd_s₁' : gcd_complexity s₁' < m := by
        have hcross : gcd_complexity s₁' = gcd_complexity (insert a rest'2) := by
          unfold gcd_complexity
          have hinj₁ : Set.InjOn liftR₁' ↑(insert a rest'2) :=
            fun x _ y _ h => (Subring.inclusion_injective hle₁) h
          rw [show s₁' = (insert a rest'2).image liftR₁' from rfl,
              Finset.sum_image hinj₁]
          apply Finset.sum_congr rfl
          intro x _
          exact normalizedFactors_card_inclusion R S₁
            ⟨hAext₁.le, hAext₁.primes_preserved, hAext₁.card_le⟩ hle₁ x
        have hstrict : gcd_complexity (insert a rest'2) < gcd_complexity (insert a rest) := by
          letI : NormalizationMonoid R.carrier :=
            UniqueFactorizationMonoid.normalizationMonoid
          unfold gcd_complexity
          rw [Finset.sum_insert ha_rest'2, Finset.sum_insert ha_rest]
          apply Nat.add_lt_add_left
          have hinj_b2 : Set.InjOn div_q_b2 ↑rest :=
            fun x hx y hy hxy => by
              have hx_eq := hdiv_b2 x (Finset.mem_coe.mp hx)
              have hy_eq := hdiv_b2 y (Finset.mem_coe.mp hy)
              calc x = q' * div_q_b2 x := hx_eq
                _ = q' * div_q_b2 y := by rw [hxy]
                _ = y := hy_eq.symm
          rw [hrest'2_def, Finset.sum_image hinj_b2]
          apply Finset.sum_lt_sum
          · intro x hx
            by_cases hx0 : x = 0
            · subst hx0
              have : div_q_b2 0 = 0 := by
                have h := hdiv_b2 0 hx
                exact (mul_eq_zero.mp h.symm).resolve_left hq'.ne_zero
              rw [this]
            · have hdvd_x : div_q_b2 x ∣ x :=
                ⟨q', (hdiv_b2 x hx).trans (mul_comm q' (div_q_b2 x))⟩
              by_cases hfx : div_q_b2 x = 0
              · simp [hfx, UniqueFactorizationMonoid.normalizedFactors_zero]
              · open UniqueFactorizationMonoid in
                exact Multiset.card_le_card
                  ((dvd_iff_normalizedFactors_le_normalizedFactors
                    hfx hx0).mp hdvd_x)
          · refine ⟨b, hb_rest, ?_⟩
            have hb_ne : b ≠ 0 := by
              intro hb0
              have h := hdiv_b2 b hb_rest
              rw [hb0] at h hdb2_zero
              exact hdb2_zero ((mul_eq_zero.mp h.symm).resolve_left hq'.ne_zero)
            have hb_eq := hdiv_b2 b hb_rest
            -- nf(b).card = 1 + nf(div_q_b2 b).card since b = q' * div_q_b2 b
            open UniqueFactorizationMonoid in
            have : (normalizedFactors b).card =
                1 + (normalizedFactors (div_q_b2 b)).card := by
              conv_lhs => rw [hb_eq]
              rw [normalizedFactors_mul hq'.ne_zero hdb2_zero, Multiset.card_add,
                normalizedFactors_irreducible (irreducible_iff_prime.mpr hq'),
                Multiset.card_singleton]
            omega
        calc gcd_complexity s₁' =
              gcd_complexity (insert a rest'2) := hcross
          _ < gcd_complexity (insert a rest) :=
              hstrict
          _ ≤ gcd_complexity s := hgcd_rest
          _ ≤ m := hs_gcd
      obtain ⟨S₂, hAext₂, hle₂, hw_S₂⟩ :=
        ih_m (gcd_complexity s₁') hgcd_s₁' S₁ hS₁_card (liftR₁' a) s₁' le_rfl hs₁'_card
          ha_s₁' w hw_s₁'
      refine ⟨S₂, hAext₂, hle₂, ?_⟩
      convert hw_S₂ using 1
      congr 1
      rw [Ideal.map_span, ← Finset.coe_image]


theorem gcd_complexity_div_prime_strict
    {R : NSubring T}
    [IsDomain R.carrier] [UniqueFactorizationMonoid R.carrier]
    [DecidableEq R.carrier]
    {a : R.carrier} {s s' : Finset R.carrier}
    (hs_insert : s = insert a s')
    (hs'_def : s' = s.erase a)
    (hs'_card_ge : 2 ≤ s'.card)
    {p : R.carrier} (hp : Prime p)
    (div_f : R.carrier → R.carrier)
    (hdiv : ∀ x ∈ s', x = p * div_f x)
    (ha_sdiv : a ∉ s'.image div_f) :
    gcd_complexity (insert a (s'.image div_f)) <
      gcd_complexity s := by
  have ha_not_s' : a ∉ s' := by
    rw [hs'_def]
    simp [Finset.mem_erase]
  letI : NormalizationMonoid R.carrier :=
    UniqueFactorizationMonoid.normalizationMonoid
  unfold gcd_complexity
  rw [Finset.sum_insert ha_sdiv, hs_insert, Finset.sum_insert ha_not_s']
  apply Nat.add_lt_add_left
  have hinj_f : Set.InjOn div_f ↑s' :=
    fun x hx y hy hxy => by
      have hx_eq := hdiv x (Finset.mem_coe.mp hx)
      have hy_eq := hdiv y (Finset.mem_coe.mp hy)
      calc x = p * div_f x := hx_eq
        _ = p * div_f y := by rw [hxy]
        _ = y := hy_eq.symm
  rw [Finset.sum_image hinj_f]
  apply Finset.sum_lt_sum
  · intro x hx
    by_cases hx0 : x = 0
    · subst hx0
      have : div_f 0 = 0 := by
        have h := hdiv 0 hx
        exact (mul_eq_zero.mp h.symm).resolve_left hp.ne_zero
      rw [this]
    · have hdvd_x : div_f x ∣ x := ⟨p, (hdiv x hx).trans (mul_comm p (div_f x))⟩
      by_cases hfx : div_f x = 0
      · simp [hfx, UniqueFactorizationMonoid.normalizedFactors_zero]
      · open UniqueFactorizationMonoid in
        exact Multiset.card_le_card
          ((dvd_iff_normalizedFactors_le_normalizedFactors
            hfx hx0).mp hdvd_x)
  · -- Strict decrease: need a nonzero element in s' (guaranteed by s'.card >= 2)
    obtain ⟨x, hx_mem, hx_ne⟩ : ∃ x ∈ s', x ≠ (0 : R.carrier) := by
      by_contra h
      push_neg at h
      have : s' ⊆ {0} :=
        fun x hx => Finset.mem_singleton.mpr (h x hx)
      have := Finset.card_le_card this
      simp at this
      omega
    refine ⟨x, hx_mem, ?_⟩
    have hfx_ne : div_f x ≠ 0 := by
      intro hfx0
      have h := hdiv x hx_mem
      rw [hfx0, mul_zero] at h
      exact hx_ne h
    have hx_eq := hdiv x hx_mem
    open UniqueFactorizationMonoid in
    have : (normalizedFactors x).card = 1 + (normalizedFactors (div_f x)).card := by
      conv_lhs => rw [hx_eq]
      rw [normalizedFactors_mul hp.ne_zero hfx_ne, Multiset.card_add,
        normalizedFactors_irreducible (irreducible_iff_prime.mpr hp), Multiset.card_singleton]
    omega

end
